name: Deploy to Firebase Hosting on PR

on: pull_request

permissions:
  contents: read
  id-token: write
  checks: write
  pull-requests: write

env:
  WORKLOAD_IDENTITY_PROVIDER: 'projects/196690008143/locations/global/workloadIdentityPools/main/providers/github'
  SERVICE_ACCOUNT: 'github@stakestar.iam.gserviceaccount.com'

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: 18
          cache: yarn
      - uses: google-github-actions/auth@v1
        id: auth
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          create_credentials_file: true
      - id: secrets
        uses: google-github-actions/get-secretmanager-secrets@v1
        with:
          secrets: |-
            github-token:stakestar/github_token
      - run: |
          echo "SERVICE_ACCOUNT_KEY=$(cat "${{ steps.auth.outputs.credentials_file_path }}" | tr -d '\n')" >> $GITHUB_ENV
      - run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ steps.secrets.outputs.github-token }}
      - run: yarn build
        env:
          INFURA_KEY: ${{ secrets.INFURA_KEY }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ env.SERVICE_ACCOUNT_KEY }}
          projectId: stakestar
