name: Release

on:
  release:
    types: [ published ]

permissions:
  contents: read
  packages: read
  id-token: write

env:
  WORKLOAD_IDENTITY_PROVIDER: 'projects/196690008143/locations/global/workloadIdentityPools/main/providers/github'
  SERVICE_ACCOUNT: 'github@stakestar.iam.gserviceaccount.com'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build
      with:
        infura_key: ${{ secrets.INFURA_KEY }}
    - uses: ./.github/actions/deploy
      with:
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}
        channel: live
        target: prod
